config/routes.rb
Dayshades::Application.routes.draw do

<<<<<<< HEAD
  resources :orders

  resources :line_items

  resources :carts

  resources :admins
  resources :categories
  resources :products
  resources :orders
  resources :customers
  resources :dashboard
  resources :administrators
=======
  get "users/index"

  get "users/new"

  get "users/edit"

  get "users/show"

  get "customers/index"

  get "customers/new"

  get "customers/show"

  get "customers/edit"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  get "administrators/index"

  get "administrators/new"

<<<<<<< HEAD
  get "administrators/show"

  get "administrators/edit"

  get "orders/index"

  get "orders/show"

  

  get "customers/index"

  get "customers/edit"

  get "customers/show"
=======
  get "administrators/edit"

  get "administrators/show"

  get "administrator/index"

  get "administrator/new"

  get "administrator/edit"

  get "administrator/show"

  get "dashboard/index"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  get "products/index"

  get "products/new"

  get "products/edit"

  get "products/show"

<<<<<<< HEAD
=======
  resources :administrators
  resources :categories
  resources :products
  resources  :dashboard
  resources :customers
  resources :users
  
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
  get "categories/edit"

  get "categories/new"

  get "categories/show"

  get "categories/index"

<<<<<<< HEAD
  get "dashboard/index"

  get "public/home"

  get "public/show"

  get "public/index"

  get "public/contact"

  get "public/instructions"

  get "public/about"

  get "public/products"

  get "public/list"
=======
  get "public/index"

  get "public/list"

  get "public/show"

  get "public/contact"

  get "public/about"

  get "public/instructions"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  root :to => 'public#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
     current_item = line_items.where(:product_id => product_id).first
     if current_item
       current_item.quantity += 1
    else
       current_item = line_items.build(:product_id => product_id)
    end
       current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
  else
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
   end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    #@cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
       format.html { redirect_to(public_list_url,
       :notice => 'Your cart is currently empty' ) }
       format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title" >Your Cart</div>
<table>
<%= render(cart.line_items) %>
<tr class="total_line" >
<td colspan="2" >Total</td>
<td class="total_cell" ><%= cart.total_price %></td>
</tr>
</table>
<%= button_to "Checkout" , new_order_path, :method => :get %>
<%= button_to 'Empty cart' , cart, :method => :delete,
:confirm => 'Are you sure?' %>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="wraptop">
  <div class="top">
        <div class="top-panel-links">
            <ul class="list-align-right">
                <li><%= link_to 'REGISTER', customers_new_path %></li>
                <li><%= link_to 'SIGN IN', "#" %></li>
                <li><%= link_to 'ADMIN', administrators_path %></li> 
                <li><%= image_tag ("facebook.png") %> </li>
                <li><%= image_tag ("twitter.png") %></li>
            </ul>
        </div>
    </div>
</div>

<div class="wrapper">
    <div class="content">
        <div class="header-row">
            <div class="logo">
                    <%= link_to (image_tag ("logo.png")), public_index_path %>
            </div>
        </div>

        <div class="row">
        	<div class="nav">
        		<ul>
        			<li><%= link_to 'HOME', public_index_path%></li>
        			<li><%= link_to 'ABOUT US', public_about_path %></li>
        			<li><%= link_to 'PRODUCTS', public_list_path %></li>
        			<li><%= link_to 'INSTRUCTIONS', public_instructions_path %></li>
        			<li><%= link_to 'CONTACT US', public_contact_path %></li>
        		</ul>
        	</div>
    	</div>
            
            <div class="row">
	            <div class="content-col">
                    <h1>Editing Carts</h1>
			            	<%= render 'form' %>

							<%= link_to 'Show', @cart %> |
							<%= link_to 'Back', carts_path %>
	            </div>
        	</div>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="wrap-footer">
	<div class="footer">
		
	</div>
</div>

<div class="bottom-wrapper">
	<div class="bottom">
		<p class="text"><%= link_to 'HOME', public_home_path%> | <%= link_to 'ABOUT US', public_about_path %> | <%= link_to 'PRODUCTS', public_products_path %> | <%= link_to 'INSTRUCTIONS', public_instructions_path %> | <%= link_to 'CONTACT US', public_contact_path %></p>

        <p>Dayshades Bridal Boutique 2013 &copy; All rights reserved. Website by | <%= link_to 'Thabang Chewa ', "http://www.thabangchewa.co.za" %> & <%= link_to 'Lebo Modimola', "http://www.twitter.com/@lebom" %> </p>
	</div>
</div>




<h

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="cart_title" >Your Cart</div>
<table>
<% for item in @cart.line_items %>
<tr>
<td><%= item.quantity %>&times;</td>
<td><%= item.product.code
%></td>
<td class="item_price" ><%= item.total_price %></td>
</tr>
<% end %>
<tr class="total_line" >
<td colspan="2" >Total</td>
<td class="total_cell" ><%= @cart.total_price %></td>
</tr>
</table>
<%= button_to 'Empty cart' , @cart, :method => :delete,
:confirm => 'Are you sure?' %>