config/routes.rb
Dayshades::Application.routes.draw do

<<<<<<< HEAD
  resources :orders

  resources :line_items

  resources :carts

  resources :admins
  resources :categories
  resources :products
  resources :orders
  resources :customers
  resources :dashboard
  resources :administrators
=======
  get "users/index"

  get "users/new"

  get "users/edit"

  get "users/show"

  get "customers/index"

  get "customers/new"

  get "customers/show"

  get "customers/edit"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  get "administrators/index"

  get "administrators/new"

<<<<<<< HEAD
  get "administrators/show"

  get "administrators/edit"

  get "orders/index"

  get "orders/show"

  

  get "customers/index"

  get "customers/edit"

  get "customers/show"
=======
  get "administrators/edit"

  get "administrators/show"

  get "administrator/index"

  get "administrator/new"

  get "administrator/edit"

  get "administrator/show"

  get "dashboard/index"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  get "products/index"

  get "products/new"

  get "products/edit"

  get "products/show"

<<<<<<< HEAD
=======
  resources :administrators
  resources :categories
  resources :products
  resources  :dashboard
  resources :customers
  resources :users
  
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
  get "categories/edit"

  get "categories/new"

  get "categories/show"

  get "categories/index"

<<<<<<< HEAD
  get "dashboard/index"

  get "public/home"

  get "public/show"

  get "public/index"

  get "public/contact"

  get "public/instructions"

  get "public/about"

  get "public/products"

  get "public/list"
=======
  get "public/index"

  get "public/list"

  get "public/show"

  get "public/contact"

  get "public/about"

  get "public/instructions"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  root :to => 'public#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :email, :name, :password, :phone

  validates_presence_of :email, :name, :password, :phone
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
<<<<<<< HEAD
  attr_accessible :email, :name, :password, :phone

  validates_presence_of :email, :name, :password, :phone
=======
  attr_accessible :confirmation, :email, :name, :password, :phone
  validates :name, :phone, :email, :password, :confirmation,	:presence 	=>	true
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
     current_item = line_items.where(:product_id => product_id).first
     if current_item
       current_item.quantity += 1
    else
       current_item = line_items.build(:product_id => product_id)
    end
       current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  attr_accessible :description, :image, :name

  validates_presence_of :description, :image, :name
<<<<<<< HEAD
=======
  
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  attr_accessible :name, :password, :password_confirmation
  validates :name, :password, :password_confirmation, presence: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  attr_accessible :address, :email, :name, :pay_type
  PAYMENT_TYPES = [ "Check" , "Credit card" , "Purchase order" ]

  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES

  def add_line_items_from_cart(cart)
     cart.line_items.each do |item|
       item.cart_id = nil
       line_items << item
     end
  end

  def add_line_items_from_cart(cart)
     cart.line_items.each do |item|
       item.cart_id = nil
       line_items << item
     end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
<<<<<<< HEAD
  default_scope :order => 'code'

  has_many :line_items
  belongs_to :categories

  before_destroy :ensure_not_referenced_by_any_line_item
  def ensure_not_referenced_by_any_line_item
  	if line_items.count.zero?
       return true
    else
       errors.add(:base, 'Line Items present' )
    return false
    end
  end

  attr_accessible :category_id, :code, :color, :fabric, :image_big, :image_thumb, :price

  validates_presence_of :category_id, :code, :color, :fabric, :image_big, :image_thumb, :price


=======

  belongs_to :categories

  attr_accessible :category_id, :code, :color, :fabric, :image_big, :image_thumb, :price

  validates_presence_of :category_id, :code, :color, :fabric, :image_big, :image_thumb, :price
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
end

app/models/user.rb
<<<<<<< HEAD

require 'digest/sha2'
class User < ActiveRecord::Base

attr_accessible :name, :password, :password_confirmation, :salt #:hashed_password

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation, :salt, :hashed_password
  attr_reader :password
  validate :password_must_be_present
  after_destroy :ensure_an_admin_remains

    def User.authenticate(name, password)
       if user = find_by_name(name)
          if user.hashed_password == encrypt_password(password, user.salt)
             user
          end
       end
    end
   
    def User.encrypt_password(password, salt)
       Digest::SHA2.hexdigest(password + "wibble" + salt)
    end

    def password=(password)
       @password = password
       if password.present?
          generate_salt
          self.hashed_password = self.class.encrypt_password(password, salt)
       end
    end

  private

    def password_must_be_present
       errors.add(:password, "Missing password" ) unless hashed_password.present?
    end

    def generate_salt
       self.salt = self.object_id.to_s + rand.to_s
    end

    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
    
  end
=======
class User < ActiveRecord::Base
  attr_accessible :address, :email, :name, :password, :phone
end
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@categories = Category.all
  	@products = Product.all
  end

  def create
  	@product = Product.new(params[:product])
  		if @product.save

        		flash[:notice]='Product information has been saved'
        		flash[:status] = true
  				redirect_to action: "index"
  			else
  				
        		flash[:notice]='Error : Could not save product in the database'
        		flash[:status] = false
        		redirect_to action: "index"
  		end
  end

  def update
    @product = Product.find(params[:id])
      if @admin.update_attributes(params[:product])
            redirect_to product_new_path, :notice => "Updated Details successfully"
        else
          
           redirect_to product_edit_path, :notice => "Unable to update details"
      end
  end

  def new
    @product = Product.new
    @products = Product.all
    @categories = Category.all
  end

  def destroy
    @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path, :notice => "Product has been deleted"
  end

  def edit
    @product = Product.find(params[:id])
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @categories = Category.all
  end
<<<<<<< HEAD
end
=======
end
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
<<<<<<< HEAD

	@home_title = "Dayshades Bridal Boutique | Home"
=======
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<<<<<<< HEAD
<%= simple_form_for @product do |p| %>
=======
<%= form_for @product do |p| %>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
		Select Category <br>
		<%= collection_select(:product, :category_id, @categories, :id, :name, {:prompt => true })  %><br><br>

		Product Code <br>
		<%= p.text_field :code, {class:"textfield"} %><br><br>

		Product Colour <br>
		<%= p.text_field :color, {class:"textfield"} %><br><br>

		Fabric Type <br>
		<%= p.text_field :fabric, {class:"textfield"} %><br><br>

		Product Thumbnail Image <br>
		<%= p.text_field :image_thumb, {class:"textfield"} %><br><br>

		Product Big Image  <br>
		<%= p.text_field :image_big, {class:"textfield"} %><br><br>

		Price <br>
		<%= p.text_field :price, {class:"textfield"} %><br><br>

		<%= submit_tag "Save", {class:"button-class"} %><br>
<% end %>

app/views/products/_form2.html.erb
<%= form_for @product do |p| %>
		            			
		            			Product Code <br>
								<%= p.text_field :code, {class:"textfield"} %><br><br>

								Product Colour <br>
								<%= p.text_field :color, {class:"textfield"} %><br><br>

								Fabric Type <br>
								<%= p.text_field :fabric, {class:"textfield"} %><br><br>

								Product Thumbnail Image <br>
								<%= p.text_field :image_thumb, {class:"textfield"} %><br><br>

								Product Big Image  <br>
								<%= p.text_field :image_big, {class:"textfield"} %><br><br>

								Price <br>
								<%= p.text_field :price, {class:"textfield"} %><br><br>

								<%= submit_tag "Save", {class:"button-class"} %><br>
						<% end %>

app/views/products/edit.html.erb
<div class="admin-top">	
	<div class="wraptop">
	  <div class="top">
	   	<div class="top-panel-logo"><h1>DAYSHADES | <span>Admin</span></h1></div>
	        
	        <div class="top-panel-links">
	        	<ul>
	            	<li><%= link_to 'DASHBOARD', dashboard_index_path %></li>
<<<<<<< HEAD
	            	<li><%= link_to 'CUSTOMERS', customers_path %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', orders_path %></li>
=======
	            	<li><%= link_to 'CUSTOMERS', "#" %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', "orders_path" %></li>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
	            	<li><%= link_to 'ADMINISTRATORS', administrators_new_path %></li>

	            </ul>
	        
	        </div>
		</div>
	</div>
</div>

<div class="admin-wrap">
	<div class="admin-content">
		<div class ="text">
			<h1>Edit Product  </h1>
				<br>
	            	<div class = "left">
	            		<strong><p class="stat-blue"><%=	flash[:notice] %></p></strong>
	            		<br><br>
		            	<%= render 'form2' %>
					</div>

					<div class="right">

						<BR><BR>
	            		<table width="850" border="0">
							<tr>
								<td class="table-header-style td-width-30px"><b> IMAGE</b></td>
								<td class="table-header-style td-width-100px"><b> COLOUR</b></td>
								<td class="table-header-style td-width-100px"><b> FABRIC</b></td>
								<td class="table-header-style td-width-100px"><b> CODE</b></td>
								<td class="table-header-style td-width-40px"><b> CATEGORY</b></td>
								<td class="table-header-style td-width-40px"><b> PRICE</b></td>
								<td class="table-header-style td-width-100px"><b> &nbsp;</b></td>
								
							</tr>
							<% @products.each do |product| %>
								<tr>
									<td class="align-center"><%= image_tag(product.image_thumb, :size => "85x100") %></td>
									<td class="align-center"><%= product.color %></td>
									<td class="align-center"><%= product.fabric %></td>
									<td class="align-center"><%= product.code %></td>
									<td class="align-center"><%= product.category_id %></td>
									<td class="align-center"><b>R<%= product.price %></b></td>
<<<<<<< HEAD
									<td class="align-center"><%= link_to 'Edit', edit_admin_path(product) %> | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
=======
									<td class="align-center"><%= link_to 'Edit', edit_products_path(product) %> | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
								</tr>
							<% end %>
						</table>
				    </div>
				    
        	</div>
        </div>
    </div>
							
</div>
<div class="clear"><br><br></div>
<div class="wrap-footer">
	<div class="footer">
		
	</div>
</div>

<div class="bottom-wrapper">
	<div class="bottom">
<<<<<<< HEAD
		<p class="text"><%= link_to 'HOME', public_home_path%> | <%= link_to 'ABOUT US', public_about_path %> | <%= link_to 'PRODUCTS', public_products_path %> | <%= link_to 'INSTRUCTIONS', public_instructions_path %> | <%= link_to 'CONTACT US', public_contact_path %></p>

=======
		
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
        <p>Dayshades Bridal Boutique 2013 &copy; All rights reserved. Website by | <%= link_to 'Thabang Chewa ', "http://www.thabangchewa.co.za" %> & <%= link_to 'Lebo Modimola', "http://www.twitter.com/@leboomm" %> </p>
	</div>
</div>

app/views/products/index.html.erb
<div class="admin-top">	
	<div class="wraptop">
	  <div class="top">
	   	<div class="top-panel-logo"><h1>DAYSHADES | <span>Admin</span></h1></div>
	        
	        <div class="top-panel-links">
	        	<ul>
	            	<li><%= link_to 'DASHBOARD', dashboard_index_path %></li>
<<<<<<< HEAD
	            	<li><%= link_to 'CUSTOMERS', customers_path %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', orders_path %></li>
=======
	            	<li><%= link_to 'CUSTOMERS', "#" %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', "orders_path" %></li>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
	            	<li><%= link_to 'ADMINISTRATORS', administrators_new_path %></li>

	            </ul>
	        
	        </div>
		</div>
	</div>
</div>

<div class="admin-wrap">
	<div class="admin-content">
		<div class ="text">
			<h1>Product List</h1>
			<br/>
			<strong><p class="stat-blue"><%=	flash[:notice] %></p></strong>
<<<<<<< HEAD
=======
			<br><br>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
				<div class = "column-right">
				<br><br>
					<table width="350" border="0">
							<tr>
								<td class="table-header-style td-width-30px"><b> ID</b></td>
								<td class="table-header-style td-width-30px"><b> IMAGE</b></td>
								<td class="table-header-style td-width-30px"><b> CATEGORY</b></td>
							</tr>
							<% @categories.each do |c| %>
							<tr>
								<td><%= c.id %></td>
								<td><%= image_tag(c.image, :size => "85x100") %></td>
								<td><%= c.name%></td>
							</tr>
							<% end %>
					</table>
				</div>

					<div class = "column-left">
					<%= link_to 'ADD NEW PRODUCT', products_new_path, {class:"button-class"} %>
					<br><br>
					<table width="800" border="0">
							<tr>
								<td class="table-header-style td-width-30px"><b> IMAGE</b></td>
								<td class="table-header-style td-width-100px"><b> COLOUR</b></td>
								<td class="table-header-style td-width-100px"><b> FABRIC</b></td>
								<td class="table-header-style td-width-100px"><b> CODE</b></td>
								<td class="table-header-style td-width-40px"><b> CATEGORY</b></td>
								<td class="table-header-style td-width-40px"><b> PRICE</b></td>
								<td width="100" class="table-header-style "><b> &nbsp;</b></td>
								
							</tr>
							<% @products.each do |product| %>
								<tr>
									<td class="align-center"><%= link_to image_tag(product.image_thumb, :size => "85x100"), product %></td>
									<td class="align-center"><%= product.color %></td>
									<td class="align-center"><%= product.fabric %></td>
									<td class="align-center"><%= product.code %></td>
									<td class="align-center"><%= product.category_id %></td>
									<td class="align-center"><b>R<%= product.price %></b></td>
									<td width="100" class="align-center"><%= link_to 'Show', product %> | <%= link_to 'Edit', edit_product_path(product) %> <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
								</tr>
							<% end %>
						</table>
	            		
				    </div>
				    
        	</div>
        </div>
    </div>
							
</div>
<div class="clear"><br><br></div>
<div class="wrap-footer">
	<div class="footer">
		
	</div>
</div>

<div class="bottom-wrapper">
	<div class="bottom">
<<<<<<< HEAD
		<p class="text"><%= link_to 'HOME', public_home_path%> | <%= link_to 'ABOUT US', public_about_path %> | <%= link_to 'PRODUCTS', public_products_path %> | <%= link_to 'INSTRUCTIONS', public_instructions_path %> | <%= link_to 'CONTACT US', public_contact_path %></p>
=======
		
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

        <p>Dayshades Bridal Boutique 2013 &copy; All rights reserved. Website by | <%= link_to 'Thabang Chewa ', "http://www.thabangchewa.co.za" %> & <%= link_to 'Lebo Modimola', "http://www.twitter.com/@leboomm" %> </p>
	</div>
</div>

app/views/products/new.html.erb
<div class="admin-top">	
	<div class="wraptop">
	  <div class="top">
	   	<div class="top-panel-logo"><h1>DAYSHADES | <span>Admin</span></h1></div>
	        
	        <div class="top-panel-links">
	        	<ul>
	            	<li><%= link_to 'DASHBOARD', dashboard_index_path %></li>
<<<<<<< HEAD
	            	<li><%= link_to 'CUSTOMERS', customers_path %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_new_path %></li>
	            	<li><%= link_to 'ORDERS', orders_path %></li>
	            	<li><%= link_to 'ADMINISTRATORS', administrators_new_path %></li>

=======
	            	<li><%= link_to 'CUSTOMERS', "#" %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', "orders_path" %></li>
	            	<li><%= link_to 'ADMINISTRATORS', administrators_new_path %></li>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
	            </ul>
	        
	        </div>
		</div>
	</div>
</div>

<div class="admin-wrap">
	<div class="admin-content">
		<div class ="text">
<<<<<<< HEAD
			<h1>Products</h1>
=======
			<h1>New Product</h1>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
				<br>
	            	<div class = "left">
	            		<strong><p class="stat-blue"><%=	flash[:notice] %></p></strong>
	            		<br><br>
		            	<%= render 'form' %>
					</div>

					<div class="right">

						<table width="850" border="0">
							<tr>
								<td class="table-header-style td-width-30px"><b> ID</b></td>
								<td class="table-header-style td-width-30px"><b> CATEGORY</b></td>
							</tr>
							<% @categories.each do |c| %>
							<tr>
								<td><%= c.id %></td>
								<td><%= c.name%></td>
							</tr>
							<% end %>
						</table>
						<BR><BR>
	            		<table width="850" border="0">
							<tr>
								<td class="table-header-style td-width-30px"><b> IMAGE</b></td>
								<td class="table-header-style td-width-100px"><b> COLOUR</b></td>
								<td class="table-header-style td-width-100px"><b> FABRIC</b></td>
								<td class="table-header-style td-width-100px"><b> CODE</b></td>
								<td class="table-header-style td-width-40px"><b> CATEGORY</b></td>
								<td class="table-header-style td-width-40px"><b> PRICE</b></td>
								<td class="table-header-style td-width-100px"><b> &nbsp;</b></td>
								
							</tr>
							<% @products.each do |product| %>
								<tr>
									<td class="align-center"><%= image_tag(product.image_thumb, :size => "85x100") %></td>
									<td class="align-center"><%= product.color %></td>
									<td class="align-center"><%= product.fabric %></td>
									<td class="align-center"><%= product.code %></td>
									<td class="align-center"><%= product.category_id %></td>
									<td class="align-center"><b>R<%= product.price %></b></td>
									<td class="align-center"><%= link_to 'Show', product %>   | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
								</tr>
							<% end %>
						</table>
				    </div>
				    
        	</div>
        </div>
    </div>
							
</div>
<div class="clear"><br><br></div>
<div class="wrap-footer">
	<div class="footer">
		
	</div>
</div>

<div class="bottom-wrapper">
	<div class="bottom">
<<<<<<< HEAD
		<p class="text"><%= link_to 'HOME', public_home_path%> | <%= link_to 'ABOUT US', public_about_path %> | <%= link_to 'PRODUCTS', public_products_path %> | <%= link_to 'INSTRUCTIONS', public_instructions_path %> | <%= link_to 'CONTACT US', public_contact_path %></p>
=======
		
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

        <p>Dayshades Bridal Boutique 2013 &copy; All rights reserved. Website by | <%= link_to 'Thabang Chewa ', "http://www.thabangchewa.co.za" %> & <%= link_to 'Lebo Modimola', "http://www.twitter.com/@leboomm" %> </p>
	</div>
</div>

app/views/products/show.html.erb
<div class="admin-top">	
	<div class="wraptop">
	  <div class="top">
	   	<div class="top-panel-logo"><h1>DAYSHADES | <span>Admin</span></h1></div>
	        
	        <div class="top-panel-links">
	        	<ul>
	            	<li><%= link_to 'DASHBOARD', dashboard_index_path %></li>
<<<<<<< HEAD
	            	<li><%= link_to 'CUSTOMERS', customers_path %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', orders_path %></li>
=======
	            	<li><%= link_to 'CUSTOMERS', "#" %></li>
	            	<li><%= link_to 'CATEGORIES', categories_path %></li>
	            	<li><%= link_to 'PRODUCTS', products_path %></li>
	            	<li><%= link_to 'ORDERS', "orders_path" %></li>
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
	            	<li><%= link_to 'ADMINISTRATORS', administrators_new_path %></li>

	            </ul>
	        
	        </div>
		</div>
	</div>
</div>

<div class="admin-wrap">
	<div class="admin-content">
		<div class ="text">
			<h1>Product Details</h1>
				<br>
	            	<div class = "column-left">
	            		
						  <%= image_tag(@product.image_big) %>
						  		
					</div>

					<div class="column-right">
						<h2>Details</h2>

						<table width="450">
							<tr>
								<td><b>ID</b></td>
								<td><b>CATEGORY</b></td>
							</tr>
							<% @categories.each do |c| %>
							<tr>
								<td><%= h(c.id) %></td>
								<td><%= h(c.name) %></td>
							</tr>
							<% end %>
						<table>

						<br>
						<table width="450">
							<tr>
								<td><b>CATEGORY ID</b></td>
								<td><%= @product.category_id %></td>
							</tr>
							<tr>
								<td><b>PRODUCT CODE</b></td>
								<td><%= @product.code.upcase %></td>
							</tr>

							<tr>
								<td><b>AVAILABLE COLOURS</b></td>
								<td><%= @product.color.upcase %></td>
							</tr>

							<tr>
								<td><b>PRODUCT FABRIC</b></td>
								<td><%= @product.fabric.upcase %></td>
							</tr>

							<tr>
								<td><b>PRICE</b></td>
								<td>R <%= @product.price %></td>
							</tr>


						</table>
	            		
				    </div>
        	</div>
        </div>
    </div>
							
</div>
<div class="clear"><br><br></div>
<div class="wrap-footer">
	<div class="footer">
		
	</div>
</div>

<div class="bottom-wrapper">
	<div class="bottom">
<<<<<<< HEAD
		<p class="text"><%= link_to 'HOME', public_home_path%> | <%= link_to 'ABOUT US', public_about_path %> | <%= link_to 'PRODUCTS', public_products_path %> | <%= link_to 'INSTRUCTIONS', public_instructions_path %> | <%= link_to 'CONTACT US', public_contact_path %></p>
=======
		
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

        <p>Dayshades Bridal Boutique 2013 &copy; All rights reserved. Website by | <%= link_to 'Thabang Chewa ', "http://www.thabangchewa.co.za" %> & <%= link_to 'Lebo Modimola', "http://www.twitter.com/@leboomm" %> </p>
	</div>
</div>