config/routes.rb
Dayshades::Application.routes.draw do

<<<<<<< HEAD
  resources :orders

  resources :line_items

  resources :carts

  resources :admins
  resources :categories
  resources :products
  resources :orders
  resources :customers
  resources :dashboard
  resources :administrators
=======
  get "users/index"

  get "users/new"

  get "users/edit"

  get "users/show"

  get "customers/index"

  get "customers/new"

  get "customers/show"

  get "customers/edit"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  get "administrators/index"

  get "administrators/new"

<<<<<<< HEAD
  get "administrators/show"

  get "administrators/edit"

  get "orders/index"

  get "orders/show"

  

  get "customers/index"

  get "customers/edit"

  get "customers/show"
=======
  get "administrators/edit"

  get "administrators/show"

  get "administrator/index"

  get "administrator/new"

  get "administrator/edit"

  get "administrator/show"

  get "dashboard/index"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  get "products/index"

  get "products/new"

  get "products/edit"

  get "products/show"

<<<<<<< HEAD
=======
  resources :administrators
  resources :categories
  resources :products
  resources  :dashboard
  resources :customers
  resources :users
  
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87
  get "categories/edit"

  get "categories/new"

  get "categories/show"

  get "categories/index"

<<<<<<< HEAD
  get "dashboard/index"

  get "public/home"

  get "public/show"

  get "public/index"

  get "public/contact"

  get "public/instructions"

  get "public/about"

  get "public/products"

  get "public/list"
=======
  get "public/index"

  get "public/list"

  get "public/show"

  get "public/contact"

  get "public/about"

  get "public/instructions"
>>>>>>> a1a6f8affd8c0f1500ac245dcdfaf5ee5e38de87

  root :to => 'public#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    #@line_item = LineItem.new(params[:line_item])

    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(@line_item.cart) }
        #format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= simple_form_for(@line_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :product_id %><br />
    <%= f.input :cart_id %><br />
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
<td><%= line_item.quantity %>&times;</td>
<td><%= line_item.product.product_name %></td>
<td class="item_price" ><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<div class="wraptop">
  <div class="top">
        <div class="top-panel-links">
            <ul class="list-align-right">
                <li><%= link_to 'REGISTER', customers_new_path %></li>
                <li><%= link_to 'SIGN IN', "#" %></li>
                <li><%= link_to 'ADMIN', administrators_path %></li> 
                <li><%= image_tag ("facebook.png") %> </li>
                <li><%= image_tag ("twitter.png") %></li>
            </ul>
        </div>
    </div>
</div>

<div class="wrapper">
    <div class="content">
        <div class="header-row">
            <div class="logo">
                    <%= link_to (image_tag ("logo.png")), public_index_path %>
            </div>
        </div>

        <div class="row">
          <div class="nav">
            <ul>
              <li><%= link_to 'HOME', public_index_path%></li>
              <li><%= link_to 'ABOUT US', public_about_path %></li>
              <li><%= link_to 'PRODUCTS', public_list_path %></li>
              <li><%= link_to 'INSTRUCTIONS', public_instructions_path %></li>
              <li><%= link_to 'CONTACT US', public_contact_path %></li>
            </ul>
          </div>
      </div>
            
            <div class="row">
              <div class="content-col">
                    <h1>Your Cart</h1>
                
                    <table width="850" border="0">
                      <tr>
                        <td class="table-header-style td-width-100px"><b> PRODUCT</b></td>
                        <td class="table-header-style td-width-100px"><b> CART</b></td>
                        <td class="table-header-style td-width-100px"><b> </b></td>
                        
                      </tr>

                    <% @line_items.each do |line_item| %>
                      <tr>
                        <td class=" td-width-100px"><%= line_item.product_id %></td>
                        <td class=" td-width-100px"><%= line_item.cart_id %></td>
                        <td class=" td-width-100px"><%= link_to 'Show', line_item %>
                        <%= link_to 'Edit', edit_line_item_path(line_item) %>
                        <%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                    </table>

                    <br />

                    <%= link_to 'New Line item', new_line_item_path,{class:"button-class"} %>
                    <BR><BR><BR>

              </div>
          </div>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="wrap-footer">
  <div class="footer">
    
  </div>
</div>

<div class="bottom-wrapper">
  <div class="bottom">
    <p class="text"><%= link_to 'HOME', public_home_path%> | <%= link_to 'ABOUT US', public_about_path %> | <%= link_to 'PRODUCTS', public_products_path %> | <%= link_to 'INSTRUCTIONS', public_instructions_path %> | <%= link_to 'CONTACT US', public_contact_path %></p>

        <p>Dayshades Bridal Boutique 2013 &copy; All rights reserved. Website by | <%= link_to 'Thabang Chewa ', "http://www.thabangchewa.co.za" %> & <%= link_to 'Lebo Modimola', "http://www.twitter.com/@lebom" %> </p>
  </div>
</div>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>